// <auto-generated />
using System;
using HepsiApi.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HepsiApi.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240222161015_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(2771),
                            IsDeleted = false,
                            Name = "Outdoors, Automotive & Computers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(2787),
                            IsDeleted = false,
                            Name = "Music, Electronics & Computers"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(2793),
                            IsDeleted = true,
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priorty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6268),
                            IsDeleted = false,
                            Name = "Elektronik",
                            ParentId = 0,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6270),
                            IsDeleted = false,
                            Name = "Moda",
                            ParentId = 0,
                            Priorty = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6272),
                            IsDeleted = false,
                            Name = "Ev,Yaşam,Kırtasiye,Ofis",
                            ParentId = 0,
                            Priorty = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6273),
                            IsDeleted = false,
                            Name = "Oto,Bahçe,Yapı Market",
                            ParentId = 0,
                            Priorty = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6274),
                            IsDeleted = false,
                            Name = "Anne,Bebek,Oyuncak",
                            ParentId = 0,
                            Priorty = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6276),
                            IsDeleted = false,
                            Name = "Spor,OutDoor",
                            ParentId = 0,
                            Priorty = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6277),
                            IsDeleted = false,
                            Name = "Kozmetik,Kişisel Bakım",
                            ParentId = 0,
                            Priorty = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6278),
                            IsDeleted = false,
                            Name = "Süpermarket, Pet Shop",
                            ParentId = 0,
                            Priorty = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6280),
                            IsDeleted = false,
                            Name = "Kitap, Müziki,Film,Hobi",
                            ParentId = 0,
                            Priorty = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6281),
                            IsDeleted = false,
                            Name = "Bilgisayar",
                            ParentId = 1,
                            Priorty = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(6282),
                            IsDeleted = false,
                            Name = "Kadın",
                            ParentId = 2,
                            Priorty = 1
                        });
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(7542),
                            Description = "IPS",
                            IsDeleted = false,
                            Title = "Ekran Panel Tipi"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(7544),
                            Description = "Mika Gümüşü",
                            IsDeleted = false,
                            Title = "Renk"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(7545),
                            Description = "GDDR6",
                            IsDeleted = true,
                            Title = "Ekran Kartı Bellek Tipi"
                        });
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(8409),
                            Description = "Test",
                            Discount = 10m,
                            IsDeleted = false,
                            Price = 1000m,
                            Title = "Test"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CreatedDate = new DateTime(2024, 2, 22, 19, 10, 14, 864, DateTimeKind.Local).AddTicks(8475),
                            Description = "Tes1t",
                            Discount = 10m,
                            IsDeleted = false,
                            Price = 1000m,
                            Title = "Test1"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("HepsiApi.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HepsiApi.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Detail", b =>
                {
                    b.HasOne("HepsiApi.Domain.Entities.Category", "category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Product", b =>
                {
                    b.HasOne("HepsiApi.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("HepsiApi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
